/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as ContactsLayoutImport } from "./routes/_contacts-layout";
import { Route as ContactsLayoutContactsImport } from "./routes/_contacts-layout/contacts";

// Create Virtual Routes

const ContactsLayoutContactIdLazyImport = createFileRoute(
  "/_contacts-layout/$contactId"
)();

// Create/Update Routes

const ContactsLayoutRoute = ContactsLayoutImport.update({
  id: "/_contacts-layout",
  getParentRoute: () => rootRoute,
} as any);

const ContactsLayoutContactIdLazyRoute =
  ContactsLayoutContactIdLazyImport.update({
    id: "/$contactId",
    path: "/$contactId",
    getParentRoute: () => ContactsLayoutRoute,
  } as any).lazy(() =>
    import("./routes/_contacts-layout/$contactId.lazy").then((d) => d.Route)
  );

const ContactsLayoutContactsRoute = ContactsLayoutContactsImport.update({
  id: "/contacts",
  path: "/contacts",
  getParentRoute: () => ContactsLayoutRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_contacts-layout": {
      id: "/_contacts-layout";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof ContactsLayoutImport;
      parentRoute: typeof rootRoute;
    };
    "/_contacts-layout/contacts": {
      id: "/_contacts-layout/contacts";
      path: "/contacts";
      fullPath: "/contacts";
      preLoaderRoute: typeof ContactsLayoutContactsImport;
      parentRoute: typeof ContactsLayoutImport;
    };
    "/_contacts-layout/$contactId": {
      id: "/_contacts-layout/$contactId";
      path: "/$contactId";
      fullPath: "/$contactId";
      preLoaderRoute: typeof ContactsLayoutContactIdLazyImport;
      parentRoute: typeof ContactsLayoutImport;
    };
  }
}

// Create and export the route tree

interface ContactsLayoutRouteChildren {
  ContactsLayoutContactsRoute: typeof ContactsLayoutContactsRoute;
  ContactsLayoutContactIdLazyRoute: typeof ContactsLayoutContactIdLazyRoute;
}

const ContactsLayoutRouteChildren: ContactsLayoutRouteChildren = {
  ContactsLayoutContactsRoute: ContactsLayoutContactsRoute,
  ContactsLayoutContactIdLazyRoute: ContactsLayoutContactIdLazyRoute,
};

const ContactsLayoutRouteWithChildren = ContactsLayoutRoute._addFileChildren(
  ContactsLayoutRouteChildren
);

export interface FileRoutesByFullPath {
  "": typeof ContactsLayoutRouteWithChildren;
  "/contacts": typeof ContactsLayoutContactsRoute;
  "/$contactId": typeof ContactsLayoutContactIdLazyRoute;
}

export interface FileRoutesByTo {
  "": typeof ContactsLayoutRouteWithChildren;
  "/contacts": typeof ContactsLayoutContactsRoute;
  "/$contactId": typeof ContactsLayoutContactIdLazyRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/_contacts-layout": typeof ContactsLayoutRouteWithChildren;
  "/_contacts-layout/contacts": typeof ContactsLayoutContactsRoute;
  "/_contacts-layout/$contactId": typeof ContactsLayoutContactIdLazyRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "" | "/contacts" | "/$contactId";
  fileRoutesByTo: FileRoutesByTo;
  to: "" | "/contacts" | "/$contactId";
  id:
    | "__root__"
    | "/_contacts-layout"
    | "/_contacts-layout/contacts"
    | "/_contacts-layout/$contactId";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  ContactsLayoutRoute: typeof ContactsLayoutRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
  ContactsLayoutRoute: ContactsLayoutRouteWithChildren,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_contacts-layout"
      ]
    },
    "/_contacts-layout": {
      "filePath": "_contacts-layout.tsx",
      "children": [
        "/_contacts-layout/contacts",
        "/_contacts-layout/$contactId"
      ]
    },
    "/_contacts-layout/contacts": {
      "filePath": "_contacts-layout/contacts.tsx",
      "parent": "/_contacts-layout"
    },
    "/_contacts-layout/$contactId": {
      "filePath": "_contacts-layout/$contactId.lazy.tsx",
      "parent": "/_contacts-layout"
    }
  }
}
ROUTE_MANIFEST_END */
